### ISSUE TITLE
help! game crush 

### ISSUE THREAD

**Issue by rMyst** [auroramod/h1-mod#994]
CPU: Ryzen 5 5600x
GPU: RTX 3050 
RAM: 32gb
OS: 11 windows 
Call of duty departure and obscure characters, despite the fact that the library is present 
qq experts, I need urgent help, so I downloaded the call of duty mv2 remaster, in the middle of act 1 I ran into the problem that the game crashes with an error after 1 of my death (I will attach the error). At the same time, the symbols are not clear, although the library is worth the whole thing. I don't know what to do, the iron seems to be fresh. The assumption at first was that there was not enough RAM, but after standing afk in the game, surprisingly it did not fly out. I don't know what to do, but I really want to play the remaster, so I'm contacting you 
![280583310_49c83a2983281bf4614c18c115034a5f_800](https://github.com/user-attachments/assets/a77b45ca-f76d-48b9-92f1-7c579d7682ad)
I didn't find the h2 mod repository, so I'm writing here

**Comment by skkuull** [comment]
https://github.com/alicealys/h2-mod
